services:
  ground_control:
    image: postgres:15-alpine
    container_name: ground_control
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: sipnscrape
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coffee_net

  sip_api:
    build: ./sip_api
    container_name: sip_api
    volumes:
      - ./sip_api:/app
      - torch_cache:/root/.cache/torch
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - ground_control
    networks:
      - coffee_net

networks:
  coffee_net:

volumes:
  postgres_data:
  torch_cache: